[package]
name = "caching_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httparse = "1.8.0"
threadpool = "1.8.1"

[profile.release]
debug = true
